// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh2Kh-7ZFLguLZnz1YGWhyzjdebiXOoWw',
    appId: '1:1094554838824:android:2ad173b59b32e37eb8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    storageBucket: 'store-7ff06.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZs7P-f0J57zJ_5c8pEY_dnmwJcFISxg',
    appId: '1:1094554838824:web:8af716026d029517b8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    authDomain: 'store-7ff06.firebaseapp.com',
    storageBucket: 'store-7ff06.appspot.com',
    measurementId: 'G-LQYW9VWJQ8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTkyCLnW_F3MwtLi88yaGYteXMbGImrFA',
    appId: '1:1094554838824:ios:a0d925feff7979dab8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    storageBucket: 'store-7ff06.appspot.com',
    androidClientId:
        '1094554838824-aac4mc75maff9pjmvtbu4b342e52nqvr.apps.googleusercontent.com',
    iosClientId:
        '1094554838824-cg3nvmr0cjohqvpnri54mh3dgbjkj18i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTkyCLnW_F3MwtLi88yaGYteXMbGImrFA',
    appId: '1:1094554838824:ios:d5a5b96249a68997b8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    storageBucket: 'store-7ff06.appspot.com',
    androidClientId:
        '1094554838824-aac4mc75maff9pjmvtbu4b342e52nqvr.apps.googleusercontent.com',
    iosClientId:
        '1094554838824-87r4rd1d8bqvqm71ltv5itd3assn86pa.apps.googleusercontent.com',
    iosBundleId: 'com.packdge.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiZs7P-f0J57zJ_5c8pEY_dnmwJcFISxg',
    appId: '1:1094554838824:web:c3d8d0e5ac58b4a6b8521d',
    messagingSenderId: '1094554838824',
    projectId: 'store-7ff06',
    authDomain: 'store-7ff06.firebaseapp.com',
    storageBucket: 'store-7ff06.appspot.com',
    measurementId: 'G-G48PZ5BMY4',
  );
}
